words = {
    # Kata Benda
    'Noun': [
        'liat', 'laib', 'adeg', 'ater', 'ider', 'ayah', 'uruk', 'arep', 'ibing', 'arit',
        'gergaji', 'rauh', 'ukir', 'tegul', 'tebus', 'beli', 'iket', 'tampi', 'uber',
        'gebug', 'kucit', 'kusir', 'togog', 'umah', 'dewa', 'pura', 'meme', 'adi',
        'tiuk', 'leak', 'raksasa', 'jukut', 'motor', 'jukung', 'emas',
        'jaring', 'uyah', 'sate', 'cedok', 'cekalan', 'kursi', 'gunung', 'angin',
        'keneh', 'sepatu', 'baju', 'tanah', 'kayu', 'atma', 'bunyi', 'suarga',
        'neraka', 'alas', 'dharma', 'taksu', 'sukerta', 'genta', 'pelawa', 'tedung',
        'guru', 'pandita', 'raja', 'teben', 'jineng', 'setra', 'tukad', 'segara',
        'canang', 'bhuana', 'bale', 'sanggah', 'pelinggih', 'natah', 'merajan', 'subak', 'carik',
        'tenget', 'balian', 'pecalang', 'kulkul', 'gamelan', 'gender', 'rindik',
        'canangsari', 'banten', 'sesajen', 'kober', 'umbul-umbul', 'gebogan',
        'pecaruan', 'padmasana', 'panggungan', 'gedong', 'paon', 'tembok',
        'lelangit', 'bantang', 'tulang', 'kulit', 'getih', 'lengen', 'lima',
        'jeroan', 'kelapa', 'base', 'don', 'bunga', 'woh', 'padang', 'abing',
        'tegal', 'uma', 'sema', 'pura', 'mrajan', 'jaba', 'kaja', 'kelod',
        'kangin', 'kauh', 'bebanten', 'tirta', 'yadnya', 'penjor', 'layangan', 'baju', 'badung',
        'sanglah', 'pasar', 'warung', 'jalikan', 'ketipat', 'jaja', 'arak', 'tuak', 
        'payuk', 'panci', 'semprong', 'kompor', 'siap', 'sampi', 'celeng', 'bangkung',
        'bikul', 'lelipi', 'katak', 'kedis', 'siap', 'bebek', 'meong', 'cicing',
        'punyan', 'entik', 'biu', 'poh', 'nangka', 'durian', 'salak', 'wani',
        'bingin', 'kepuh', 'delima', 'sumaga', 'jeruk', 'belimbing', 'nyuh',
        'jagung', 'padi', 'kacang', 'ketela', 'kesela', 'tabia', 'bawang',
        'jahe', 'kunyit', 'lengkuas', 'cengkeh', 'pala', 'kemiri', 'kayu',
        'jelanan', 'ampik', 'kakus', 'undagan', 'sinduk', 'caratan', 'sembe', 'yeh',
        'endut', 'bias', 'bulaan', 'tiing', 'celagih', 'gadung', 'kesuna', 'jepun',
        'gelang', 'kalung', 'subeng', 'udeng', 'kamben', 'saput', 'daksina', 'kajang',
        'dulang', 'sokasi', 'tamiang', 'sampian', 'bebed', 'bebungkilan', 'kebaya',
        'wastra', 'umpal', 'tepeng', 'kuskusan', 'dangdang', 'paso', 'jun', 'gentong',
        'pane', 'kekeb', 'kau', 'tempeh', 'penarak', 'bokor', 'wadah', 'pabuan',
        'cecepan', 'coblong', 'lumur', 'kecer', 'kendang', 'suling', 'gong', 'kempur',
        'kempli', 'gangsa', 'kantil', 'jegog', 'klentung', 'keropak', 'lontar',
        'prasi', 'pecanangan', 'sibuh', 'pedupaan', 'plangkiran', 'dapetan', 'penuntun',
        'telabah', 'carik', 'pekaseh', 'pemangku', 'klian', 'penjor', 'sanggah',
        'pelinggih', 'palinggih', 'tumpek', 'galungan', 'kuningan', 'saraswati',
        'pekarangan', 'tetaring', 'kelir', 'langse', 'aling-aling', 'klatkat',
        'pemesuan', 'pemrajan', 'piasan', 'penyengker', 'angkul-angkul', 'candi',
        'kori', 'tapakan', 'kemulan', 'taksu', 'rong', 'tugu', 'palih', 'undag',
        'pengubengan', 'pangapit', 'pamedal', 'jogan', 'saka', 'sunduk', 'sineb',
        'tetekeh', 'tiang', 'tugeh', 'dedari', 'penunggu', 'balian', 'tapel',
        'rangda', 'barong', 'jauk', 'telek', 'topeng', 'legong', 'pendet',
        'rejang', 'baris', 'sanghyang', 'kecak', 'gambuh', 'arja', 'wayang',
        'dalang', 'geguntangan', 'kendang', 'cengceng', 'gangsa', 'reong',
        'trompong', 'kajar', 'kempul', 'kemong', 'jegogan', 'jublag', 'penyacah',
        'kantilan', 'pemade', 'kenong', 'kelentang', 'kelentung',
        'kekawin', 'kidung', 'geguritan', 'peparikan', 'sendor', 'sunari', 'sesapi',
        'rebab', 'seruling', 'cendekan', 'pepesan', 'lawar', 'betutu', 'urutan',
        'timbungan', 'bantal', 'tum', 'sate', 'komoh', 'rujak', 'sambal', 'jukut',
        'pesan', 'gecok', 'urab', 'serombotan', 'plecing', 'sambel', 'sumping',
        'jaja', 'dodol', 'begina', 'satuh', 'bendu', 'lempog', 'klepon', 'tulung',
        'nagasari', 'apem', 'bubuh', 'tepeng', 'timpan', 'laklak', 'panggang',
        'pepes', 'urap', 'blayag', 'temisi', 'besisit', 'timbung', 'saur', 'siap',
        'gedang', 'belimbing', 'ceroring', 'delima', 'durén', 'jambu', 'juét',
        'manggis', 'nangka', 'nyambu', 'paya', 'sotong', 'tibah', 'wani',
        'bengkuang', 'boni', 'buluan', 'bunut', 'kepundung', 'kuweni', 'sentul',
        'silik', 'srikaya', 'sukun', 'tin', 'tingkih', 'timbul', 'rambutan', 'sekolah',
        'alit-alite'
    ],
    # Kata Kerja
    'Verb': [
        'melajah', 'megae', 'maplalian', 'nulis', 'memaca', 'melaib', 'mejalan',
        'negak', 'megedi', 'ulung', 'ngajeng', 'minum', 'teka', 'atoang', 'menek',
        'ngaturang', 'muspa', 'mabanten', 'ngayah', 'metanding', 'ngigel', 'makekawin',
        'makidung', 'nganteb', 'ngaturang', 'mategen', 'malayang', 'nanding',
        'ngastawa', 'masemayut', 'ngarga', 'ngamel', 'ngoton', 'masolah', 'ngocek',
        'nyurat', 'ngukir', 'nyangih', 'mesuara', 'nganggit', 'ngepung',
        'majalan', 'merebah', 'mebikas', 'mekamben', 'mesaput', 'ngaturang',
        'ngayah', 'metajen', 'megambel', 'megending', 'mekumpul', 'mebanten',
        'mekarya', 'ngadol', 'numbas', 'madaar', 'ngidih', 'nyilih', 'ngutang',
        'ngadep', 'ngisidang', 'mesuun', 'negul', 'ningalin', 'ngerasang', 
        'nguberin', 'numbas', 'nongos', 'ajak',
        'ngebah', 'nyangkol', 'nuturang', 'ngenah', 'ningeh', 'ngadek',
        'ngecap', 'ngetel', 'ngutang', 'nyemak', 'ngejang', 'nyemak', 'ngaba',
        'ngateh', 'nyarup', 'ngecum', 'nginem', 'medaar', 'masare',
        'medem', 'bangun', 'matangi', 'makecos', 'makecog', 'makejer', 'magebur',
        'majemuh', 'ngendih', 'ngenyat', 'ngedum', 'ngecek', 'ngraos',
        'matutur', 'masesandan', 'makeengan', 'makisid', 'makeber', 'nglayang',
        'nyiksik', 'nyangket', 'ngejer', 'ngebug', 'nglungo', 'majalan', 'melaib',
        'nglangi', 'ngeling','ngamah', 'nyiup', 'negakin', 'nulungin', 'nyampat', 'ngumbah', 'nyemak',
        'ngungsi', 'nganteg', 'ngetep', 'ngaukin', 'nulad', 'nguruk', 'nyuun',
        'nyangkil', 'nengok', 'ningting', 'nyangkol', 'ngetok', 'ngibukang',
        'nyarmin', 'ngangget', 'nyangket', 'ngutgut', 'ngesges', 'ngebut',
        'ngepung', 'nyemuh', 'nguyak', 'nyangih', 'ngungkab', 'ngebet', 'nguncab',
        'ngebang', 'nyedut', 'ngampik', 'ngejer', 'ngengap', 'ngecum', 'ngukud',
        'ngenahang', 'ngisinin', 'ngorahang', 'mangenang', 'makeneh', 'masadu',
        'mapagin', 'mapitulung', 'maplalian', 'makepung', 'maboros', 'masiluman',
        'matetulung', 'mapalalian', 'masayuban', 'matatakan', 'mabanten', 'masuryak',
        'mabelasan', 'mapinunas', 'masemadi', 'mayoga', 'makemit', 'masekar',
        'mawangsit', 'masaur', 'mapaica', 'mabakti', 'mapuja', 'manamiu',
        'ngadukang', 'ngecapang', 'ngebitang', 'ngorahin', 'nunden', 'nyemakang',
        'ngaenang', 'nyangkepang', 'ngadanin', 'nyelepin', 'ngelengin', 'nyagjagin',
        'nulungin', 'ngajahin', 'ngurukang', 'nyaruang', 'ngwanenang', 'makedeng',
        'makedekan', 'makenyem', 'makenyung', 'makelimat', 'maplisahan', 'makacakan',
        'maketelun', 'maketelun', 'makerah', 'makecos', 'makecuh', 'makejer',
        'maketak', 'makuuk', 'masemu', 'mekipe', 'mekenyung', 'mekecos', 'mekedek',
        'mekekeh', 'melaib', 'melali', 'meluah', 'memanting', 'memanah', 'memula',
        'menekdek', 'menesek', 'mengkeb', 'mengopak', 'menjit', 'mentik', 'mepalu',
        'mepaluing', 'mepanah', 'mepanting', 'mepatut', 'mepelud', 'mepusuh',
        'merasa', 'merengin', 'mesangih', 'mesaut', 'meseke', 'mesiat', 'metanem',
        'metanding', 'metangkis', 'metelik', 'metimpuh', 'metincak', 'metugel',
        'ngampakang', 'ngebatang', 'ngenjuhin', 'ngedasang', 'ngempelang', 'ngendihang',
        'ngaturin', 'ngaryanin', 'ngetanang', 'ngulungang', 'ngungkulin', 'nyagiang',
        'nyalimburang', 'nyampahang', 'nyangongot', 'nyantenang', 'nyapsapang', 'nyarunang',
        'nyaryanin', 'nyeberang', 'nyeburang', 'nyedotang', 'nyelepang', 'nyelselang',
        'nyempalin', 'nyengsegang', 'nyiarang', 'nyihnayang', 'nyilakang', 'nyinahang',
        'nyiupang', 'nyujukang', 'nyulamin', 'nyumpenayang', 'nyungkanang', 'nyuryakin',
        'masesolahan', 'masayuban', 'masemayan', 'masesangi', 'masesapan', 'masisigan',
        'matektekan', 'matetemahan', 'matirtayan', 'matulungan', 'mawangsalan', 'mawewalen',
        'mayasakala', 'mayunan', 'mebedelan', 'meberatan', 'mecaratan', 'medagangan',
        'megambahan', 'megangsaran', 'megegenderan', 'megocekan', 'megulingan', 'mejaguran',
        'mejogedan', 'mekalangan', 'mekampihan', 'mekantenan', 'mekenyungan', 'meketisan',
        'melayangan', 'melinggihan', 'melumahan', 'memangkalan', 'memarekan', 'memarekang',
        'memargiang', 'memiyasang', 'menadiang', 'menekang', 'mengadanin', 'mengajahin',
        'mengalahang', 'mengawinang', 'mengebatang', 'mengenahang', 'mengengkebang',
        'mengetisang', 'mengisidang', 'mengulungang', 'menikayang', 'menimpahang',
        'menjatiang', 'menyahayang', 'menyaruang', 'menyediaang', 'menyemakang',
        'menyerahang', 'mepaliang', 'mepasang', 'mepeteng', 'mepetengin', 'mepineh',
        'mepitutur', 'meplalian', 'meraksa', 'meratengang', 'merawat', 'merebat',
        'merepat', 'mesuryak', 'metakon', 'metanduran', 'metangiang', 'metegenan',
        'meteked', 'metelekan', 'metelik', 'metemung', 'metengkejut', 'metetulung',
        'metimbal', 'metingkah', 'metombok', 'metunun', 'meturut', 'mewacana',
        'mewangsit', 'mewasta', 'meyasakala', 'meyasa', 'nampedang', 'nampenin',
        'nampiang', 'nandesang', 'nandiang', 'nandingang', 'nandurin', 'nanenayang',
        'nanggapin', 'nanggiang', 'nangkenang', 'nangkidang', 'nangkilin',
        'ngamenekang', 'ngarepang', 'ngedengang', 'ngedilang', 'ngejotin', 'ngekadang',
        'ngematiang', 'ngemasin', 'ngempelin', 'ngempetin', 'ngempelang', 'ngencakang',
        'ngendahang', 'ngenjuhin', 'ngentenang', 'ngentikang', 'ngenyudang', 'ngerehang',
        'ngerusuhin', 'ngesenggang', 'ngesorang', 'ngetakang', 'ngetelang', 'ngetuhang',
        'ngewangang', 'ngicenin', 'ngidupang', 'ngilehin', 'ngilingin', 'ngimpasin',
        'ngindayang', 'ngintipang', 'ngisiang', 'ngisidang', 'ngitungang', 'ngiwasin',
        'nglanturang', 'nglemesin', 'nglepasang', 'nglinggihang', 'ngojarang', 'ngomong',
        'ngonemin', 'ngorahang', 'ngortain', 'ngosong', 'ngoyong', 'ngubadin', 'ngubuhin',
        'nguduhin', 'ngulapin', 'ngulatin', 'nguliang', 'ngulurin', 'ngumpulang',
        'ngumpulin', 'ngundebang', 'ngundigang', 'nguntulang', 'ngupayang', 'nguratiang',
        'ngurukang', 'ngutangag', 'ngutsahayang', 'nguwuhin', 'nyelapang', 'nyelempang', 
        'malajah', 'makarya', 'meli', 'meliang', 'ngai', 'ngelah', 'ngamaang', 'nyemakang',
        'polih', 'numbas', 'dados', 'magae', 'nongos', 'luas',
    ],
    'Adj': [
        'alus', 'becik', 'bagus', 'endah', 'gede', 'luas', 'lemah', 'sugih', 'dueg',
        'siteng', 'kenyel', 'banyol', 'mayus', 'ajum', 'bedak', 'seduk', 'betek', 'jaen',
        'barak',
        'ayu', 'jegeg', 'bagus', 'kasub', 'wayah', 'nguda', 'tua', 'bajang',
        'lacur', 'sukil', 'melah', 'jele', 'suci', 'leteh', 'pingit', 'umum',
        'tenget', 'angker', 'sakti', 'wisesa', 'weruh', 'wikan', 'pradnyan',
        'tambet', 'belog', 'ririh', 'jemet', 'mayus', 'demen', 'gedeg', 'sebet',
        'liang', 'emed', 'seleg', 'anteng', 'ramé', 'suung', 'tegeh', 'endep',
        'lantang', 'bawak', 'linggah', 'cupit', 'teleb', 'dayuh', 'anyar',
        'suba', 'tusing', 'nenten', 'lungha', 'rauh', 'peteng', 'galang',
        'jelek', 'beneh', 'patut', 'demen', 'gedeg', 'sebet', 'emed', 'nguda',
        'tua', 'wayah', 'rare', 'cerik', 'kelih', 'gede', 'cenik', 'mokoh',
        'berag', 'keras', 'aluh', 'keren', 'lanying', 'demen', 'jengah', 'sungsut',
        'inguh', 'ibuk', 'sengsara', 'bagia', 'lascarya', 'kejem', 'galak',
        'someh', 'ramah', 'darma', 'adil', 'polos', 'jujur', 'dusta', 'lengit',
        'ilang', 'telah', 'rumpuh', 'seger', 'kebus', 'dingin', 'nyem', 'jemet',
        'males', 'kirangan', 'tabah'
    ],
    'Adv': [
        'kapah', 'sesai', 'dibi', 'benjang', 'kejep', 'tuni', 'puan', 'nyanan',
        'jani', 'semengan', 'tengai', 'sanja', 'wengi',
        'mangkin', 'durung', 'sampun', 'dados', 'nénten', 'gelis', 'alon',
        'becik', 'payu', 'malu', 'sekat', 'uwug', 'rihin', 'pegat', 'telat',
        'enggal', 'serod', 'selid', 'tutug', 'lantas', 'malih', 'kewala',
        'nanghing', 'sakadi', 'minab', 'munguin', 'sasidan', 'wiakti', 'yakti',
        'sajawi', 'sadurung', 'sampunika', 'sapunika', 'asapunika', 'sapunapi',
        'asapunapi', 'menawi', 'meneng', 'meled', 'ngiring', 'dumun', 'mangda',
        'mangkin', 'raris', 'wusan', 'wawu', 'kantun', 'dados',
        'durung', 'kapah', 'malih',
        'nadaksara', 'prajani', 'gelis-gelis', 'alon-alon', 'adeng-adeng',
        'sai-sai', 'pepes', 'terus', 'lantas', 'malih', 'buin', 'suba', 'mara',
        'wau', 'durung', 'nenten', 'ten', 'tusing', 'ngiring', 'dados',
        'bisa', 'prasida', 'mampuh', 'nyidayang', 'sabenehne', 'sayuwakti',
        'sajatine', 'sujatine', 'wiakti', 'sekadi', 'minakadi', 'kadi', 'sakadi',
        'pateh', 'patuh', 'soroh', 'minab', 'jenenga', 'pepes', 'ping', 'wantah',
        'wenten', 'kantun', 'ngararis', 'raris', 'mangkin', 'pisan', 'jagi'
    ],
    'Prep': [
        'ring', 'ba', 'ka', 'saking', 'uli', 'duk', 'olih',
        'di', 'ke', 'uli', 'sig', 'antuk', 'maring', 'marep',
        'duri', 'beten', 'duur', 'tengah', 'samping', 'sisi', 'jaba',
        'kelod', 'kaja', 'kangin', 'kauh', 'tengahan', 'sisin', 'sedin',
        'bucun', 'diwangan', 'sajabaning', 'sajeroning', 'ring ajeng', 'ring duri',
        'ring tengah', 'ring sisin', 'ring bucun', 'ka jaba', 'ka jeroan',
        'saking jaba', 'saking jeroan', 'olih ring', 'rauh ring', 'kantos ring',
        'ngantos ring', 'sadurung ring', 'sasampun ring', 'sajabaning ring',
        'sajeroning ring', 'sane ring', 'sane maring', 'sane antuk', 'ring', 'di',
        'margi', 'ngangin', 'ngauh', 'ngaja', 'ngelod', 'menek', 'tuun',
        'kebet', 'kelawan', 'sareng', 'teken', 'ajak', 'kayang', 'kanti',
        'sambil', 'sedekan', 'sedek', 'risedek', 'rikala', 'dugase', 'dugas',
        'daweg', 'ritatkala', 'olih', 'antuk', 'maring', 'sareng',
        'teken', 'ajak', 'ngajak', 'bareng', 'ngiring', 'sameton', 'nyama',
        'braya', 'kulawarga', 'kadang', 'wargi', 'arsa', 'sumeken', 
        'sajeroning', 'tengahing', 'ngawit', 'kayang', 'rauh'
    ],
    'Pronoun': [
        'tiang', 'cang', 'iragane', 'ci', 'ia', 'ida', 'nyane', 'kami', 'iraga',
        'idane', 'dane', 'nenten', 'nikanne', 'ikane', 'sapa', 
        'puniki', 'punapi', 'titiang', 'icang', 'kai', 'jerone', 'ragane', 'gusi',
        'cai', 'iba', 'ipun',
        'gelah', 'dewek', 'awakne', 'ida-dane', 'sira', 'ipun-ipun', 'rerama',
        'okane', 'putrane', 'okan-okane', 'putran-putrane', 'ragan-ragane',
        'sami', 'samian', 'samiyan', 'sinamian', 'parasida', 'parasami',
        'parajana', 'parajanma', 'parajero', 'parasane', 'paranirane',
        'parasapasira', 'parasapasami', 'puniku', 
        'punikune', 'niki', 'nika', 'niku',
        'sira-sira', 'sapasira', 'sapasami', 'sapunapi-sapunapi',
        'manira', 'gelah', 'nira', 'ira', 'ratu', 'cokor', 'palungguh',
        'dane', 'rerama', 'meme', 'bapa', 'biang', 'aji', 'bibi',
        'uwa', 'pekak', 'dadong', 'kakiang', 'niang', 'embok', 'beli',
        'misan', 'mindon', 'kumpi', 'buyut', 'canggah', 'wareng', 'kelab',
        'uduh', 'klabang', 'gantung', 'siwer', 'ratu', 'dewa', 'betara',
        'widhi', 'hyang', 'ida', 'dané', 'ragané', 'titiang',
        'iragang', 'gelahé', 'awakné', 'dewekné', 'ragané', 'idané'
    ],
    'Det': [
        'niki', 'nika', 'puniki', 'punika', 'ene', 'ento', 'ne', 'to',
        'anu', 'ane', 'punikine', 'punikane', 'punikune', 'nikine', 'nikane',
        'nikune', 'niki-nika', 'puniki-punika'
    ],
    'Num': [
        # Cardinal numbers
        'besik', 'kalih', 'tiga', 'papat', 'lima', 'nem', 'pitu', 'kutus', 'sia', 'dasa',
        # Ordinal numbers
        'kapertama', 'kaping kalih', 'kaping tiga', 'kaping papat', 'kaping lima',
        # Collective numbers
        'aketi', 'asiu', 'ayu', 'atus', 'adasa',
        # Fractional numbers
        'aparo', 'duang paro', 'telung paro'
    ]
}