cfg_rules = {
    'K': [['S', 'P'], ['S', 'P', 'Pel'], ['S', 'P', 'Ket'], ['S', 'P', 'Pel', 'Ket']],
    'S': [['NP']],
    'P': [['PP'], ['VP']],
    'Pel': [['VP'], ['NP'], ['Aux', 'Adv'], ['Aux', 'NP']],
    'Ket': [['PP'], ['Adv']],
    'NP': [['Noun'], ['PropNoun'], ['Pronoun'], ['NP', 'Noun'], ['NP', 'PropNoun'], 
           ['NP', 'Pronoun'], ['Det', 'NP'], ['NP', 'Det'], ['NP', 'Adj'], ['NP', 'PP']],
    'PP': [['Prep', 'NP'], ['Prep', 'Adv'], ['PP', 'NumP'], ['PP', 'Adv']],
    'VP': [['Verb'], ['Verb', 'VP'], ['Verb', 'NP'], ['Adv', 'VP'], ['Aux', 'VP'], ['Aux', 'Verb']],
    'NumP': [['Num'], ['NumP', 'NP'], ['NP', 'NumP']],
    'Prep': [['ka'], ['uli'], ['di'], ['saking'], ['ring'], ['uling'], ['ke']],
    'Aux': [['dados'], ['sebilang'], ['prasida'], ['dadi'], ['sesai'], ['sampun'], 
            ['pisan'], ['paling'], ['sane'], ['setata'], ['kapah'], ['lakar']],
    'Adv': [['tuni'], ['semengan'], ['ibi'], ['sanja'], ['taun'], ['wai'], ['semeng'], 
            ['peteng'], ['sue'], ['akeh'], ['seleg'], ['dueg'], ['galak']],
    'Noun': [['carik'], ['padi'], ['sekolah'], ['sepeda'], ['kantor'], ['desa'], ['kampus'], 
             ['tukang'], ['desan'], ['pasar'], ['dosen'], ['nasi'], ['ajengan'], ['siap'], 
             ['ukud'], ['diri'], ['umah'], ['tingkat'], ['kamarne'], ['matematika'], ['komputer'], 
             ['baju'], ['tukad'], ['balian'], ['mahasiswa'], ['wewantenan'], ['sepedane'], 
             ['motorne'], ['goreng'], ['pasang'], ['kota']],
    'PropNoun': [['ketut'], ['bagus'], ['yogyakarta'], ['perbekel'], ['guru'], ['camat'], 
                 ['kuta'], ['selatan'], ['jimbaran'], ['parkir'], ['pns'], ['luh'], ['sari'], 
                 ['serombolan'], ['wayan'], ['darta'], ['ketua'], ['putu'], ['dangin'], ['gede'], 
                 ['udayana'], ['unda'], ['puspa'], ['surabaya']],
    'Pronoun': [['bapan'], ['bapak'], ['bu'], ['pak'], ['adin'], ['titiang'], ['ia'], 
                ['timpal-timpal'], ['kulawarga'], ['ibu'], ['timpal'], ['memen'], ['tiange'], 
                ['memene'], ['adine'], ['pianakne'], ['bapane'], ['bapakne'], ['ragane'], 
                ['dane'], ['ipune'], ['anake']],
    'Det': [['i'], ['punika'], ['pinaka'], ['ento']],
    'Adj': [['selem'], ['demenin'], ['becik'], ['luung'], ['jegeg'], ['jegeg-jegeg'], 
            ['sakti'], ['baru']],
    'Verb': [['nanem'], ['ngatehin'], ['ngalihin'], ['melajah'], ['masepedaan'], ['nganggon'], 
             ['meli'], ['anggone'], ['rauh'], ['ngatur'], ['meblanja'], ['megambal'], ['melali'], 
             ['mekarya'], ['manting'], ['ngajahin'], ['abane']],
    'Num': [['2020'], ['pitung'], ['telung'], ['limang'], ['dadue']]
}